(let ((my-packages '(init-loader
                     ;; ace-jump-mode
                     avy
                     ag
                     wgrep-ag
                     all-ext
                     anzu
                     auto-complete
                     auto-save-buffers-enhanced
                     bm
                     coffee-mode
                     color-moccur
                     neotree
                     direx
                     dash-at-point
                     dockerfile-mode
                     exec-path-from-shell
                     expand-region
                     evil
                     elixir-mode
                     alchemist
                     flycheck
                     go-mode
                     go-errcheck
                     go-eldoc
                     go-direx
                     go-autocomplete
                     golint
                     gotest
                     gist
                     git-gutter-fringe
                     diff-hl
                     header2
                     helm
                     helm-ag
                     helm-bm
                     helm-c-yasnippet
                     helm-descbinds
                     helm-ghq
                     helm-ls-git
                     helm-migemo
                     auto-highlight-symbol
                     highlight-symbol
                     inf-ruby
                     json-mode
                     key-chord
                     less-css-mode
                     magit
                     markdown-mode
                     migemo
                     multiple-cursors
                     open-junk-file
                     org
                     org-journal
                     ox-gfm
                     php-mode
                     popwin
                     powershell
                     projectile
                     helm-projectile
                     quickrun
                     rainbow-mode
                     search-web
                     shell-pop
                     rbenv
                     recentf-ext
                     region-bindings-mode
                     ruby-test-mode
                     rspec-mode
                     minitest
                     rubocop
                     rust-mode
                     slim-mode
                     sass-mode
                     sequential-command
                     shell-command
                     smart-compile
                     smartparens
                     smartrep
                     sml-modeline
                     sql-indent
                     toml-mode
                     undo-tree
                     viewer
                     volatile-highlights
                     web-mode
                     whitespace-cleanup-mode
                     yaml-mode
                     yard-mode
                     yasnippet
                     zencoding-mode
                     zop-to-char)))
  (dolist (x my-packages)
    (when (not (package-installed-p x))
      (package-install x))))
