(ensure-package-installed 'auto-save-buffers-enhanced)
(require 'auto-save-buffers-enhanced)
;; (auto-save-buffers-enhanced-include-only-checkout-path t)
(setq auto-save-buffers-enhanced-exclude-regexps '("^/ssh:" "/sudo:" "/multi:"))
(auto-save-buffers-enhanced t)
