;; (auto-install-batch "auto-complete")
(require 'auto-complete)
(global-auto-complete-mode t)
(setq ac-auto-start nil)
(global-set-key "\M-/" 'ac-start)
(define-key ac-complete-mode-map "\C-n" 'ac-next)
(define-key ac-complete-mode-map "\C-p" 'ac-previous)
